begin;
create extension if not exists pgtap with schema extensions;
select plan(186);

select has_table('public','livestock_groups','livestock groups table exists');
select has_table('public','livestock_events','append-only livestock events table exists');
select has_table('public','machine_assets','machine assets table exists');
select has_table('public','machine_events','machine events table exists');
select has_table('public','financial_entries','financial ledger table exists');
select has_table('public','operational_audit_events','operational audit table exists');
select has_view('public','operational_summary','operational summary view exists');
select has_table('public','ai_analysis_runs','auditable intelligence run table exists');
select has_table('public','ai_analysis_feedback','intelligence feedback table exists');
select has_view('public','latest_ai_analysis','latest intelligence view exists');
select has_table('public','maintenance_work_orders','fleet work orders table exists');
select has_table('public','maintenance_work_order_events','append-only work order history exists');
select has_table('public','satellite_analysis_runs','auditable satellite runs table exists');
select has_table('public','parcel_satellite_metrics','parcel spectral metrics table exists');
select has_table('public','satellite_timeseries_runs','earth time series runs exist');
select has_table('public','parcel_index_baselines','lot-own satellite baselines exist');
select has_table('public','weather_daily_observations','daily weather archive table exists');
select has_view('public','parcel_earth_series','earth time read model exists');
select has_table('public','irrigation_events','declared irrigation ledger exists');
select has_table('public','water_balance_runs','water balance runs exist');
select has_table('public','parcel_water_balances','parcel water balances exist');
select has_view('public','latest_parcel_water_balances','latest water balances view exists');
select has_table('public','terrain_relief_runs','terrain relief runs exist');
select has_table('public','parcel_terrain_metrics','parcel terrain metrics exist');
select has_view('public','latest_parcel_terrain_metrics','latest terrain metrics view exists');
select has_view('public','latest_terrain_relief_runs','latest terrain runs view exists');
select has_table('public','outcome_cycles','outcome cycles exist');
select has_table('public','outcome_cycle_events','outcome cycle events exist');
select has_view('public','outcome_ledger_summary','outcome ledger summary view exists');
select has_table('public','scouting_visits','scouting visits table exists');
select has_table('public','scouting_visit_events','append-only scouting visit history exists');
select has_table('public','scouting_findings','append-only field findings table exists');
select has_table('public','scouting_finding_media','private scouting evidence metadata exists');
select has_table('public','scouting_media_scans','field evidence scans exist');
select has_column('public','scouting_finding_media','scan_verdict','scouting media persist scan verdict');
select has_column('public','scouting_finding_media','scan_algorithm_version','scouting media persist scan algorithm');
select has_column('public','scouting_finding_media','scan_providers','scouting media persist scan providers');
select has_table('public','organization_invitations','organization invitations table exists');
select has_table('public','organization_security_events','organization security audit exists');
select has_table('public','pilot_programs','pilot programs table exists');
select has_table('public','pilot_snapshots','immutable pilot snapshots exist');
select has_table('public','pilot_value_claims','pilot value claims ledger exists');
select has_table('public','pilot_audit_events','pilot audit trail exists');

select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='livestock_groups'),true,'livestock groups has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='livestock_events'),true,'livestock events has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='machine_assets'),true,'machine assets has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='machine_events'),true,'machine events has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='financial_entries'),true,'financial entries has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='operational_audit_events'),true,'audit events has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='ai_analysis_runs'),true,'intelligence runs have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='ai_analysis_feedback'),true,'intelligence feedback has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='maintenance_work_orders'),true,'fleet work orders have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='maintenance_work_order_events'),true,'work order events have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='satellite_analysis_runs'),true,'satellite runs have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='parcel_satellite_metrics'),true,'satellite metrics have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='satellite_timeseries_runs'),true,'earth time runs have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='parcel_index_baselines'),true,'earth time baselines have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='weather_daily_observations'),true,'daily weather archive has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='irrigation_events'),true,'irrigation events have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='water_balance_runs'),true,'water balance runs have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='parcel_water_balances'),true,'parcel water balances have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='terrain_relief_runs'),true,'terrain relief runs have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='parcel_terrain_metrics'),true,'parcel terrain metrics have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='outcome_cycles'),true,'outcome cycles have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='outcome_cycle_events'),true,'outcome cycle events have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='scouting_visits'),true,'scouting visits have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='scouting_visit_events'),true,'scouting history has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='scouting_findings'),true,'scouting findings have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='scouting_finding_media'),true,'scouting evidence metadata has RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='scouting_media_scans'),true,'field evidence scans have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='organization_invitations'),true,'organization invitations have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='organization_security_events'),true,'organization security events have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='pilot_programs'),true,'pilot programs have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='pilot_snapshots'),true,'pilot snapshots have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='pilot_value_claims'),true,'pilot value claims have RLS enabled');
select is((select relrowsecurity from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='pilot_audit_events'),true,'pilot audit has RLS enabled');

select is(has_table_privilege('authenticated','public.livestock_groups','INSERT'),false,'authenticated cannot bypass livestock RPC');
select is(has_table_privilege('authenticated','public.machine_assets','UPDATE'),false,'authenticated cannot directly alter machine state');
select is(has_table_privilege('authenticated','public.financial_entries','INSERT'),false,'authenticated cannot directly write the ledger');
select is(has_table_privilege('authenticated','public.financial_entries','DELETE'),false,'authenticated cannot delete ledger entries');
select is(has_table_privilege('authenticated','public.operational_audit_events','INSERT'),false,'authenticated cannot forge audit events');
select is(has_table_privilege('authenticated','public.ai_analysis_runs','INSERT'),false,'browser cannot forge intelligence runs');
select is(has_table_privilege('authenticated','public.ai_analysis_runs','UPDATE'),false,'browser cannot alter intelligence outputs');
select is(has_table_privilege('authenticated','public.ai_analysis_feedback','INSERT'),false,'feedback must pass through the guarded RPC');
select is(has_table_privilege('authenticated','public.maintenance_work_orders','INSERT'),false,'browser cannot bypass work order RPC');
select is(has_table_privilege('authenticated','public.maintenance_work_orders','UPDATE'),false,'browser cannot alter work order state directly');
select is(has_table_privilege('authenticated','public.maintenance_work_order_events','INSERT'),false,'browser cannot forge work order history');
select is(has_table_privilege('authenticated','public.satellite_analysis_runs','INSERT'),false,'browser cannot forge satellite runs');
select is(has_table_privilege('authenticated','public.satellite_analysis_runs','UPDATE'),false,'browser cannot alter satellite runs');
select is(has_table_privilege('authenticated','public.parcel_satellite_metrics','INSERT'),false,'browser cannot forge satellite metrics');
select is(has_table_privilege('authenticated','public.parcel_satellite_metrics','UPDATE'),false,'browser cannot alter satellite metrics');
select ok(has_table_privilege('authenticated','public.satellite_analysis_runs','SELECT'),'members can inspect satellite runs');
select ok(has_table_privilege('authenticated','public.parcel_satellite_metrics','SELECT'),'members can inspect satellite metrics');
select is(has_table_privilege('authenticated','public.satellite_timeseries_runs','INSERT'),false,'browser cannot forge earth time runs');
select is(has_table_privilege('authenticated','public.parcel_index_baselines','INSERT'),false,'browser cannot forge lot baselines');
select is(has_table_privilege('authenticated','public.weather_daily_observations','INSERT'),false,'browser cannot forge daily rainfall');
select is(has_table_privilege('authenticated','public.satellite_timeseries_runs','UPDATE'),false,'browser cannot alter earth time runs');
select ok(has_table_privilege('authenticated','public.satellite_timeseries_runs','SELECT'),'members can inspect earth time runs');
select ok(has_table_privilege('authenticated','public.parcel_index_baselines','SELECT'),'members can inspect lot baselines');
select is(has_function_privilege('authenticated','public.refresh_parcel_index_baselines(uuid,text,text)','EXECUTE'),false,'browser cannot recompute satellite baselines');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='parcel_earth_series'),'earth time view runs with invoker security');
select is(has_table_privilege('authenticated','public.irrigation_events','INSERT'),false,'browser cannot forge irrigation events');
select is(has_table_privilege('authenticated','public.water_balance_runs','INSERT'),false,'browser cannot forge water runs');
select is(has_table_privilege('authenticated','public.parcel_water_balances','INSERT'),false,'browser cannot forge water balances');
select is(has_table_privilege('authenticated','public.terrain_relief_runs','INSERT'),false,'browser cannot forge terrain runs');
select is(has_table_privilege('authenticated','public.parcel_terrain_metrics','INSERT'),false,'browser cannot forge terrain metrics');
select is(has_table_privilege('authenticated','public.terrain_relief_runs','UPDATE'),false,'browser cannot alter terrain runs');
select is(has_table_privilege('authenticated','public.parcel_terrain_metrics','UPDATE'),false,'browser cannot alter terrain metrics');
select is(has_table_privilege('authenticated','public.outcome_cycles','INSERT'),false,'browser cannot forge outcome cycles');
select is(has_table_privilege('authenticated','public.outcome_cycle_events','INSERT'),false,'browser cannot forge outcome events');
select is(has_table_privilege('authenticated','public.outcome_cycles','UPDATE'),false,'browser cannot alter outcome cycles');
select is(has_table_privilege('authenticated','public.irrigation_events','UPDATE'),false,'browser cannot alter irrigation events');
select ok(has_table_privilege('authenticated','public.irrigation_events','SELECT'),'members can inspect irrigation events');
select ok(has_function_privilege('authenticated','public.record_irrigation_event(uuid,uuid,date,numeric,irrigation_method,text,uuid)','EXECUTE'),'authenticated role can declare guarded irrigation');
select ok(has_function_privilege('authenticated','public.reverse_irrigation_event(uuid,text,uuid)','EXECUTE'),'authenticated role can reverse guarded irrigation');
select ok((select pg_get_constraintdef(oid) like '%irrigation_event%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_entity_type_check'),'central audit accepts irrigation events');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='latest_parcel_water_balances'),'latest water balances view runs with invoker security');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='latest_parcel_terrain_metrics'),'latest terrain metrics view runs with invoker security');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='latest_terrain_relief_runs'),'latest terrain runs view runs with invoker security');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='outcome_ledger_summary'),'outcome summary view runs with invoker security');
select ok(has_function_privilege('authenticated','public.open_outcome_cycle(uuid,text,outcome_signal_kind,uuid,text,uuid)','EXECUTE'),'authenticated can open guarded outcome cycles');
select ok(has_function_privilege('authenticated','public.review_outcome_cycle(uuid,boolean,text,uuid)','EXECUTE'),'authenticated managers can review outcome cycles');
select ok(has_function_privilege('authenticated','public.set_recommendation_status(uuid,recommendation_status,text)','EXECUTE'),'authenticated can decide recommendations that spawn outcome cycles');
select is(pg_get_function_result('public.set_recommendation_status(uuid,public.recommendation_status,text)'::regprocedure),'uuid','accepting a recommendation returns an outcome cycle id');
select ok((select pg_get_constraintdef(oid) like '%outcome_cycle%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_entity_type_check'),'central audit accepts outcome cycles');
select is(has_table_privilege('authenticated','public.scouting_visits','INSERT'),false,'browser cannot bypass scouting RPC');
select is(has_table_privilege('authenticated','public.scouting_visit_events','INSERT'),false,'browser cannot forge scouting history');
select is(has_table_privilege('authenticated','public.scouting_findings','INSERT'),false,'browser cannot forge field findings');
select is(has_table_privilege('authenticated','public.scouting_finding_media','INSERT'),false,'browser cannot attach evidence metadata directly');
select is(has_table_privilege('authenticated','public.scouting_finding_media','UPDATE'),false,'browser cannot alter evidence metadata');
select ok(has_table_privilege('authenticated','public.scouting_finding_media','SELECT'),'members can inspect authorized evidence metadata');
select is(has_table_privilege('authenticated','public.scouting_media_scans','INSERT'),false,'browser cannot forge field scans');
select is(has_table_privilege('authenticated','public.scouting_media_scans','UPDATE'),false,'browser cannot alter field scans');
select ok(has_table_privilege('authenticated','public.scouting_media_scans','SELECT'),'members can inspect authorized field scans');
select is(has_function_privilege('authenticated','public.record_scouting_media_scan_server(uuid,uuid,uuid,text,text,scouting_scan_verdict,text,text[],jsonb,jsonb,jsonb,uuid)','EXECUTE'),false,'browser cannot record field scans');
select ok(has_function_privilege('service_role','public.record_scouting_media_scan_server(uuid,uuid,uuid,text,text,scouting_scan_verdict,text,text[],jsonb,jsonb,jsonb,uuid)','EXECUTE'),'service role can persist field scans');
select is(has_table_privilege('authenticated','public.organization_invitations','SELECT'),false,'browser cannot enumerate invitation tokens');
select is(has_table_privilege('authenticated','public.organization_invitations','INSERT'),false,'browser cannot forge organization invitations');
select is(has_table_privilege('authenticated','public.organization_invitations','UPDATE'),false,'browser cannot alter invitation state directly');
select is(has_table_privilege('authenticated','public.organization_invitations','DELETE'),false,'browser cannot delete invitation history');
select ok(has_table_privilege('authenticated','public.organization_security_events','SELECT'),'authenticated managers can inspect security events through RLS');
select is(has_table_privilege('authenticated','public.pilot_programs','INSERT'),false,'browser cannot launch pilots outside guarded RPC');
select is(has_table_privilege('authenticated','public.pilot_snapshots','INSERT'),false,'browser cannot forge pilot measurements');
select is(has_table_privilege('authenticated','public.pilot_value_claims','INSERT'),false,'browser cannot forge value claims directly');
select is(has_table_privilege('authenticated','public.pilot_audit_events','INSERT'),false,'browser cannot forge pilot audit events');
select ok(has_table_privilege('authenticated','public.pilot_programs','SELECT'),'members can inspect authorized pilot programs');
select ok(has_table_privilege('authenticated','public.pilot_snapshots','SELECT'),'members can inspect authorized pilot evidence');
select ok(has_table_privilege('authenticated','public.pilot_value_claims','SELECT'),'members can inspect authorized value claims');

select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='operational_summary'),'operational summary runs with invoker security');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='latest_ai_analysis'),'latest intelligence view runs with invoker security');
select ok(has_function_privilege('authenticated','public.submit_ai_analysis_feedback(uuid,ai_feedback_rating,text)','EXECUTE'),'authenticated role can call guarded intelligence feedback RPC');
select ok(has_function_privilege('authenticated','public.reverse_financial_entry(uuid,text,uuid)','EXECUTE'),'authenticated role can call guarded reversal RPC');
select ok(has_function_privilege('authenticated','public.create_machine_work_order(uuid,maintenance_work_type,text,text,maintenance_priority,date,text,numeric,uuid)','EXECUTE'),'authenticated role can create guarded work orders');
select ok(has_function_privilege('authenticated','public.transition_machine_work_order(uuid,maintenance_work_order_status,text,numeric,uuid)','EXECUTE'),'authenticated role can transition guarded work orders');
select is(has_function_privilege('authenticated','public.create_scouting_visit(uuid,uuid,uuid,text,text,scouting_priority,timestamp with time zone,uuid)','EXECUTE'),false,'legacy self-assignment RPC is disabled');
select ok(has_function_privilege('authenticated','public.create_scouting_visit_v2(uuid,uuid,uuid,text,text,scouting_priority,timestamp with time zone,uuid,uuid)','EXECUTE'),'authenticated role can create assigned scouting visits');
select ok(has_function_privilege('authenticated','public.list_scouting_assignees(uuid)','EXECUTE'),'members can list the tenant-scoped Scout directory');
select ok(has_function_privilege('authenticated','public.reassign_scouting_visit(uuid,uuid,uuid)','EXECUTE'),'authenticated role can call guarded reassignment');
select is(has_function_privilege('authenticated','private.can_operate_scouting_visit(uuid,uuid,uuid)','EXECUTE'),false,'browser cannot bypass assigned-visit authorization helper');
select ok(has_function_privilege('authenticated','public.transition_scouting_visit(uuid,scouting_visit_status,text,uuid)','EXECUTE'),'authenticated role can transition guarded scouting visits');
select ok(has_function_privilege('authenticated','public.record_scouting_finding(uuid,scouting_finding_category,scouting_severity,timestamp with time zone,double precision,double precision,double precision,text,uuid)','EXECUTE'),'authenticated role can record guarded field findings');
select is(has_function_privilege('authenticated','public.attach_scouting_media_server(uuid,text,text,text,bigint,text,text,timestamp with time zone,text,uuid,uuid)','EXECUTE'),false,'browser cannot call the service-only media attachment function');
select ok(has_function_privilege('authenticated','public.list_organization_team(uuid)','EXECUTE'),'authenticated managers can call the guarded team directory');
select ok(has_function_privilege('authenticated','public.accept_organization_invitation(uuid)','EXECUTE'),'authenticated users can accept an email-bound invitation');
select ok(has_function_privilege('authenticated','public.change_organization_member_role(uuid,uuid,organization_role,uuid)','EXECUTE'),'authenticated managers can call guarded role changes');
select ok(has_function_privilege('authenticated','public.remove_organization_member(uuid,uuid,uuid)','EXECUTE'),'authenticated managers can call guarded offboarding');
select ok(has_function_privilege('authenticated','public.revoke_organization_invitation(uuid,uuid)','EXECUTE'),'authenticated managers can revoke pending invitations');
select is(has_function_privilege('authenticated','public.prepare_organization_invitation_server(uuid,text,organization_role,timestamp with time zone,uuid,uuid)','EXECUTE'),false,'browser cannot prepare server-owned invitations');
select is(has_function_privilege('authenticated','public.mark_organization_invitation_delivery_server(uuid,text,uuid,text)','EXECUTE'),false,'browser cannot forge invitation delivery state');
select is(has_function_privilege('authenticated','public.lookup_organization_invitation_user_server(uuid)','EXECUTE'),false,'browser cannot enumerate existing Auth users through invitations');
select ok(has_function_privilege('authenticated','public.launch_pilot_program(uuid,text,text,text,date,integer,uuid)','EXECUTE'),'authenticated managers can call guarded pilot launch');
select ok(has_function_privilege('authenticated','public.capture_pilot_snapshot(uuid,uuid)','EXECUTE'),'authorized operators can capture server-owned pilot evidence');
select ok(has_function_privilege('authenticated','public.transition_pilot_program(uuid,pilot_program_status,text,uuid)','EXECUTE'),'authenticated managers can close a pilot through its state machine');
select ok(has_function_privilege('authenticated','public.record_pilot_value_claim(uuid,pilot_value_category,numeric,text,text,uuid)','EXECUTE'),'authenticated managers can declare value through guarded RPC');
select ok(has_function_privilege('authenticated','public.review_pilot_value_claim(uuid,boolean,text,uuid)','EXECUTE'),'authenticated managers can review value through guarded RPC');
select is(has_function_privilege('authenticated','private.build_pilot_metrics(uuid,date,date)','EXECUTE'),false,'browser cannot call the server-owned pilot metric builder');
select is(has_function_privilege('authenticated','private.pilot_limitations()','EXECUTE'),false,'browser cannot bypass the pilot limitations contract');
select ok((select pg_get_constraintdef(oid) like '%maintenance_work_order%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_entity_type_check'),'central audit accepts fleet work orders');
select ok((select pg_get_constraintdef(oid) like '%scouting_finding%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_entity_type_check'),'central audit accepts scouting entities');
select ok((select pg_get_constraintdef(oid) like '%scouting_media%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_entity_type_check'),'central audit accepts private scouting media');
select ok((select pg_get_constraintdef(oid) like '%scouting_scan%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_entity_type_check'),'central audit accepts field scans');
select ok((select pg_get_constraintdef(oid) like '%scan_blocked%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_action_check'),'central audit accepts blocked field scans');
select ok((select pg_get_constraintdef(oid) like '%assignment_changed%' from pg_constraint where conrelid='public.operational_audit_events'::regclass and conname='operational_audit_events_action_check'),'central audit accepts Scout assignment changes');
select ok((select pg_get_constraintdef(oid) like '%assigned%' from pg_constraint where conrelid='public.scouting_visit_events'::regclass and conname='scouting_visit_events_action_check'),'Scout history accepts reassignment events');
select is((select public from storage.buckets where id='scouting-evidence'),false,'scouting evidence bucket is private');
select ok((select 'security_invoker=true'=any(coalesce(reloptions,array[]::text[])) from pg_class join pg_namespace on pg_namespace.oid=pg_class.relnamespace where nspname='public' and relname='operational_summary'),'fleet summary keeps invoker security');

select * from finish();
rollback;
