import { useMemo, useState, type FormEvent } from 'react';
import { ArrowDownRight, ArrowUpRight, Beef, CalendarClock, CircleDollarSign, ClipboardPlus, History, LoaderCircle, RotateCcw, ShieldCheck, Tractor, Wrench } from 'lucide-react';
import { useCreateLivestockGroup, useCreateMachineAsset, useRecordFinancialEntry, useRecordLivestockEvent, useRecordMachineEvent, useReverseFinancialEntry, type FinancialEntry, type LivestockEvent, type MachineEvent, type Workspace } from './lib/workspace';
import './operations.css';

const nowForInput=()=>{const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16)};
const todayForInput=()=>new Date().toISOString().slice(0,10);
const formatNumber=(value:number,decimals=0)=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:decimals}).format(Number(value));
const formatMoney=(value:number,currency:string)=>new Intl.NumberFormat('es-AR',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value));
const eventDate=(value:string)=>new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const mutationMessage=(error:unknown)=>error instanceof Error?error.message:'No se pudo completar la operación';

const livestockEventLabels:Record<LivestockEvent['event_type'],string>={initial_stock:'Stock inicial',birth:'Nacimientos',purchase:'Compra',sale:'Venta',mortality:'Mortandad',transfer_in:'Ingreso',transfer_out:'Egreso',adjustment:'Ajuste',weighing:'Pesaje'};
const machineEventLabels:Record<MachineEvent['event_type'],string>={usage:'Uso',service:'Service',repair:'Reparación',inspection:'Inspección'};
const kindLabels:Record<string,string>={tractor:'Tractor',harvester:'Cosechadora',implement:'Implemento',vehicle:'Vehículo',pump:'Bomba',generator:'Generador',other:'Otro'};

function ModuleHeader({eyebrow,title,description,action,actionLabel}:{eyebrow:string;title:string;description:string;action:()=>void;actionLabel:string}){
  return <div className="moduleToolbar"><div><small>{eyebrow}</small><h2>{title}</h2><p>{description}</p></div><button onClick={action}><ClipboardPlus/> {actionLabel}</button></div>;
}

function MutationError({error}:{error:unknown}){return error?<p className="operationError">{mutationMessage(error)}</p>:null}
function SubmitButton({pending,label}:{pending:boolean;label:string}){return <button className="primaryOperation" disabled={pending}>{pending?<LoaderCircle className="spin"/>:<ShieldCheck/>}{pending?'Guardando…':label}</button>}

export function LivestockPanel({data}:{data:Workspace}){
  const createGroup=useCreateLivestockGroup();
  const recordEvent=useRecordLivestockEvent();
  const [creating,setCreating]=useState(data.livestockGroups.length===0);
  const [eventGroup,setEventGroup]=useState<string|null>(null);
  const [groupForm,setGroupForm]=useState({name:'',species:'cattle',category:'Vacas',headCount:'',averageWeight:'',parcelId:'',observedAt:nowForInput(),notes:''});
  const [eventForm,setEventForm]=useState({eventType:'birth',quantity:'',averageWeight:'',occurredAt:nowForInput(),reason:''});
  const activeGroups=data.livestockGroups.filter(group=>group.status==='active');
  const totalHeads=activeGroups.reduce((sum,group)=>sum+Number(group.head_count),0);
  const weightedKg=activeGroups.reduce((sum,group)=>sum+Number(group.average_weight_kg??0)*Number(group.head_count),0);
  const weighedHeads=activeGroups.reduce((sum,group)=>sum+(group.average_weight_kg?Number(group.head_count):0),0);

  function submitGroup(event:FormEvent){
    event.preventDefault();
    createGroup.mutate({establishmentId:data.establishment!.id,parcelId:groupForm.parcelId||null,name:groupForm.name,species:groupForm.species as 'cattle',category:groupForm.category,headCount:Number(groupForm.headCount),averageWeightKg:groupForm.averageWeight?Number(groupForm.averageWeight):null,observedAt:new Date(groupForm.observedAt).toISOString(),notes:groupForm.notes},{onSuccess:()=>{setCreating(false);setGroupForm({...groupForm,name:'',headCount:'',averageWeight:'',notes:'',observedAt:nowForInput()})}});
  }

  function submitEvent(event:FormEvent){
    event.preventDefault();
    if(!eventGroup)return;
    const eventType=eventForm.eventType as Exclude<LivestockEvent['event_type'],'initial_stock'>;
    const entered=Number(eventForm.quantity||0);
    const headChange=eventType==='weighing'?0:['sale','mortality','transfer_out'].includes(eventType)?-Math.abs(entered):eventType==='adjustment'?entered:Math.abs(entered);
    recordEvent.mutate({groupId:eventGroup,eventType,occurredAt:new Date(eventForm.occurredAt).toISOString(),headChange,averageWeightKg:eventForm.averageWeight?Number(eventForm.averageWeight):null,reason:eventForm.reason},{onSuccess:()=>{setEventGroup(null);setEventForm({eventType:'birth',quantity:'',averageWeight:'',occurredAt:nowForInput(),reason:''})}});
  }

  return <section className="operationsModule">
    <ModuleHeader eyebrow="TRAZABILIDAD DEL RODEO" title="Rodeo por grupos" description="Stock derivado de altas, bajas, traslados y pesajes; cada cambio conserva su evento." action={()=>setCreating(value=>!value)} actionLabel={creating?'Cerrar alta':'Nuevo grupo'}/>
    <div className="operationsKpis"><article><small>CABEZAS ACTIVAS</small><strong>{formatNumber(totalHeads)}</strong><span>{activeGroups.length} grupos</span></article><article><small>PESO PROMEDIO PONDERADO</small><strong>{weighedHeads?`${formatNumber(weightedKg/weighedHeads,1)} kg`:'—'}</strong><span>{weighedHeads?`${formatNumber(weighedHeads)} cabezas con pesaje`:'Sin pesajes registrados'}</span></article><article><small>ÚLTIMA NOVEDAD</small><strong>{data.livestockEvents[0]?eventDate(data.livestockEvents[0].occurred_at):'—'}</strong><span>{data.livestockEvents[0]?livestockEventLabels[data.livestockEvents[0].event_type]:'Sin eventos'}</span></article></div>
    {creating&&<form className="operationForm" onSubmit={submitGroup}><div className="formTitle"><Beef/><div><h3>Alta de grupo</h3><p>El stock inicial genera automáticamente el primer evento auditable.</p></div></div><div className="operationGrid">
      <label>Nombre<input required minLength={2} maxLength={100} value={groupForm.name} onChange={e=>setGroupForm({...groupForm,name:e.target.value})} placeholder="Ej. Vacas madres"/></label>
      <label>Especie<select value={groupForm.species} onChange={e=>setGroupForm({...groupForm,species:e.target.value})}><option value="cattle">Bovinos</option><option value="sheep">Ovinos</option><option value="goat">Caprinos</option><option value="horse">Equinos</option><option value="other">Otra</option></select></label>
      <label>Categoría<input required minLength={2} maxLength={60} value={groupForm.category} onChange={e=>setGroupForm({...groupForm,category:e.target.value})} placeholder="Ej. Vaquillonas"/></label>
      <label>Cabezas<input required min={1} step={1} type="number" value={groupForm.headCount} onChange={e=>setGroupForm({...groupForm,headCount:e.target.value})}/></label>
      <label>Peso promedio (kg)<input min={1} step="0.1" type="number" value={groupForm.averageWeight} onChange={e=>setGroupForm({...groupForm,averageWeight:e.target.value})} placeholder="Opcional"/></label>
      <label>Lote<select value={groupForm.parcelId} onChange={e=>setGroupForm({...groupForm,parcelId:e.target.value})}><option value="">Sin asignar</option>{data.parcels.map(parcel=><option key={parcel.id} value={parcel.id}>{parcel.name}</option>)}</select></label>
      <label>Observado el<input required type="datetime-local" value={groupForm.observedAt} onChange={e=>setGroupForm({...groupForm,observedAt:e.target.value})}/></label>
      <label className="wideField">Notas<textarea maxLength={1000} value={groupForm.notes} onChange={e=>setGroupForm({...groupForm,notes:e.target.value})} placeholder="Origen, raza o criterio de agrupación"/></label>
    </div><MutationError error={createGroup.error}/><SubmitButton pending={createGroup.isPending} label="Crear grupo y stock inicial"/></form>}
    <div className="assetList">{data.livestockGroups.length?data.livestockGroups.map(group=>{const parcel=data.parcels.find(item=>item.id===group.parcel_id);return <article className="assetCard" key={group.id}><div className="assetIcon"><Beef/></div><div className="assetBody"><div><span className={`stateTag ${group.status}`}>{group.status==='active'?'Activo':'Cerrado'}</span><h3>{group.name}</h3><p>{group.category} · {parcel?.name??'Sin lote asignado'}</p></div><div className="assetFacts"><span><b>{formatNumber(group.head_count)}</b> cabezas</span><span><b>{group.average_weight_kg?`${formatNumber(group.average_weight_kg,1)} kg`:'—'}</b> peso promedio</span><span><b>{eventDate(group.last_observed_at)}</b> última observación</span></div></div><button className="secondaryOperation" disabled={group.status==='closed'} onClick={()=>setEventGroup(eventGroup===group.id?null:group.id)}>Registrar novedad</button></article>}):<div className="operationEmpty"><Beef/><h3>No hay rodeo registrado</h3><p>Creá el primer grupo únicamente con datos del establecimiento.</p></div>}</div>
    {eventGroup&&<form className="operationForm eventForm" onSubmit={submitEvent}><div className="formTitle"><History/><div><h3>Novedad de {data.livestockGroups.find(group=>group.id===eventGroup)?.name}</h3><p>El stock resultante se calcula y valida en PostgreSQL.</p></div></div><div className="operationGrid">
      <label>Tipo<select value={eventForm.eventType} onChange={e=>setEventForm({...eventForm,eventType:e.target.value})}>{Object.entries(livestockEventLabels).filter(([key])=>key!=='initial_stock').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      {eventForm.eventType!=='weighing'&&<label>{eventForm.eventType==='adjustment'?'Variación con signo':'Cantidad'}<input required type="number" min={eventForm.eventType==='adjustment'?undefined:1} step={1} value={eventForm.quantity} onChange={e=>setEventForm({...eventForm,quantity:e.target.value})}/></label>}
      <label>Peso promedio (kg)<input required={eventForm.eventType==='weighing'} min={1} step="0.1" type="number" value={eventForm.averageWeight} onChange={e=>setEventForm({...eventForm,averageWeight:e.target.value})} placeholder={eventForm.eventType==='weighing'?'Requerido':'Opcional'}/></label>
      <label>Fecha y hora<input required type="datetime-local" value={eventForm.occurredAt} onChange={e=>setEventForm({...eventForm,occurredAt:e.target.value})}/></label>
      <label className="wideField">Motivo / documento<textarea maxLength={500} value={eventForm.reason} onChange={e=>setEventForm({...eventForm,reason:e.target.value})}/></label>
    </div><MutationError error={recordEvent.error}/><SubmitButton pending={recordEvent.isPending} label="Registrar evento"/></form>}
    {data.livestockEvents.length>0&&<article className="historyPanel"><div className="historyTitle"><History/><div><h3>Últimos movimientos</h3><p>Bitácora inmutable del establecimiento</p></div></div>{data.livestockEvents.slice(0,8).map(item=><div className="historyRow" key={item.id}><span>{livestockEventLabels[item.event_type]}</span><b>{item.head_delta>0?'+':''}{item.head_delta} cabezas</b><small>{data.livestockGroups.find(group=>group.id===item.group_id)?.name??'Grupo histórico'} · {eventDate(item.occurred_at)}</small><strong>Saldo {item.resulting_head_count}</strong></div>)}</article>}
  </section>;
}

export function MachineryPanel({data}:{data:Workspace}){
  const createAsset=useCreateMachineAsset();
  const recordEvent=useRecordMachineEvent();
  const [creating,setCreating]=useState(data.machineAssets.length===0);
  const [eventMachine,setEventMachine]=useState<string|null>(null);
  const [assetForm,setAssetForm]=useState({name:'',kind:'tractor',manufacturer:'',model:'',serialNumber:'',modelYear:'',currentHours:'0',serviceInterval:'250',lastServiceHours:'0'});
  const [eventForm,setEventForm]=useState({eventType:'usage',usageHours:'',occurredAt:nowForInput(),notes:''});
  const dueAssets=data.machineAssets.filter(asset=>asset.status!=='retired'&&Number(asset.current_hours)>=Number(asset.last_service_hours)+Number(asset.service_interval_hours));

  function submitAsset(event:FormEvent){event.preventDefault();createAsset.mutate({establishmentId:data.establishment!.id,name:assetForm.name,kind:assetForm.kind as 'tractor',manufacturer:assetForm.manufacturer,model:assetForm.model,serialNumber:assetForm.serialNumber,modelYear:assetForm.modelYear?Number(assetForm.modelYear):null,currentHours:Number(assetForm.currentHours),serviceIntervalHours:Number(assetForm.serviceInterval),lastServiceHours:Number(assetForm.lastServiceHours)},{onSuccess:()=>{setCreating(false);setAssetForm({...assetForm,name:'',model:'',serialNumber:''})}})}
  function submitEvent(event:FormEvent){event.preventDefault();if(!eventMachine)return;recordEvent.mutate({machineId:eventMachine,eventType:eventForm.eventType as MachineEvent['event_type'],occurredAt:new Date(eventForm.occurredAt).toISOString(),usageHours:eventForm.eventType==='usage'?Number(eventForm.usageHours):0,notes:eventForm.notes},{onSuccess:()=>{setEventMachine(null);setEventForm({eventType:'usage',usageHours:'',occurredAt:nowForInput(),notes:''})}})}

  return <section className="operationsModule"><ModuleHeader eyebrow="ACTIVOS Y MANTENIMIENTO" title="Maquinaria" description="Horómetros, utilización y servicios con historial; el vencimiento se calcula desde datos registrados." action={()=>setCreating(value=>!value)} actionLabel={creating?'Cerrar alta':'Nuevo activo'}/>
    <div className="operationsKpis"><article><small>ACTIVOS OPERATIVOS</small><strong>{data.machineAssets.filter(asset=>asset.status!=='retired').length}</strong><span>{data.machineAssets.length} registrados</span></article><article className={dueAssets.length?'warningKpi':''}><small>SERVICE VENCIDO</small><strong>{dueAssets.length}</strong><span>{dueAssets.length?'Requieren planificación':'Mantenimiento al día'}</span></article><article><small>HORAS ACUMULADAS</small><strong>{formatNumber(data.machineAssets.reduce((sum,asset)=>sum+Number(asset.current_hours),0),1)}</strong><span>Lectura consolidada de horómetros</span></article></div>
    {creating&&<form className="operationForm" onSubmit={submitAsset}><div className="formTitle"><Tractor/><div><h3>Alta de activo</h3><p>Identidad técnica y política inicial de mantenimiento.</p></div></div><div className="operationGrid">
      <label>Nombre<input required minLength={2} maxLength={100} value={assetForm.name} onChange={e=>setAssetForm({...assetForm,name:e.target.value})} placeholder="Ej. Tractor principal"/></label><label>Tipo<select value={assetForm.kind} onChange={e=>setAssetForm({...assetForm,kind:e.target.value})}>{Object.entries(kindLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Fabricante<input maxLength={100} value={assetForm.manufacturer} onChange={e=>setAssetForm({...assetForm,manufacturer:e.target.value})}/></label><label>Modelo<input maxLength={100} value={assetForm.model} onChange={e=>setAssetForm({...assetForm,model:e.target.value})}/></label><label>Número de serie<input maxLength={120} value={assetForm.serialNumber} onChange={e=>setAssetForm({...assetForm,serialNumber:e.target.value})}/></label><label>Año<input type="number" min={1950} max={2100} value={assetForm.modelYear} onChange={e=>setAssetForm({...assetForm,modelYear:e.target.value})}/></label><label>Horómetro actual<input required type="number" min={0} step="0.1" value={assetForm.currentHours} onChange={e=>setAssetForm({...assetForm,currentHours:e.target.value})}/></label><label>Intervalo service (h)<input required type="number" min={1} step="0.1" value={assetForm.serviceInterval} onChange={e=>setAssetForm({...assetForm,serviceInterval:e.target.value})}/></label><label>Último service (h)<input required type="number" min={0} step="0.1" value={assetForm.lastServiceHours} onChange={e=>setAssetForm({...assetForm,lastServiceHours:e.target.value})}/></label>
    </div><MutationError error={createAsset.error}/><SubmitButton pending={createAsset.isPending} label="Crear activo"/></form>}
    <div className="assetList">{data.machineAssets.length?data.machineAssets.map(asset=>{const due=asset.status!=='retired'&&Number(asset.current_hours)>=Number(asset.last_service_hours)+Number(asset.service_interval_hours);const remaining=Number(asset.last_service_hours)+Number(asset.service_interval_hours)-Number(asset.current_hours);return <article className={`assetCard ${due?'assetDue':''}`} key={asset.id}><div className="assetIcon"><Tractor/></div><div className="assetBody"><div><span className={`stateTag ${due?'maintenance':asset.status}`}>{due?'Service vencido':asset.status}</span><h3>{asset.display_name}</h3><p>{[asset.manufacturer,asset.model,asset.model_year].filter(Boolean).join(' · ')||kindLabels[asset.kind]}</p></div><div className="assetFacts"><span><b>{formatNumber(asset.current_hours,1)} h</b> horómetro</span><span><b>{due?`${formatNumber(Math.abs(remaining),1)} h vencido`:`${formatNumber(remaining,1)} h`}</b> próximo service</span><span><b>{asset.serial_number??'—'}</b> serie</span></div></div><button className="secondaryOperation" onClick={()=>setEventMachine(eventMachine===asset.id?null:asset.id)}>Registrar actividad</button></article>}):<div className="operationEmpty"><Tractor/><h3>No hay maquinaria registrada</h3><p>Agregá los activos reales para controlar utilización y mantenimiento.</p></div>}</div>
    {eventMachine&&<form className="operationForm eventForm" onSubmit={submitEvent}><div className="formTitle"><Wrench/><div><h3>Actividad de {data.machineAssets.find(asset=>asset.id===eventMachine)?.display_name}</h3><p>Los servicios actualizan la base del próximo vencimiento.</p></div></div><div className="operationGrid"><label>Tipo<select value={eventForm.eventType} onChange={e=>setEventForm({...eventForm,eventType:e.target.value})}>{Object.entries(machineEventLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{eventForm.eventType==='usage'&&<label>Horas utilizadas<input required type="number" min="0.1" step="0.1" value={eventForm.usageHours} onChange={e=>setEventForm({...eventForm,usageHours:e.target.value})}/></label>}<label>Fecha y hora<input required type="datetime-local" value={eventForm.occurredAt} onChange={e=>setEventForm({...eventForm,occurredAt:e.target.value})}/></label><label className="wideField">Detalle<textarea maxLength={1000} value={eventForm.notes} onChange={e=>setEventForm({...eventForm,notes:e.target.value})}/></label></div><MutationError error={recordEvent.error}/><SubmitButton pending={recordEvent.isPending} label="Registrar actividad"/></form>}
    {data.machineEvents.length>0&&<article className="historyPanel"><div className="historyTitle"><CalendarClock/><div><h3>Bitácora de maquinaria</h3><p>Últimos eventos registrados</p></div></div>{data.machineEvents.slice(0,8).map(item=><div className="historyRow" key={item.id}><span>{machineEventLabels[item.event_type]}</span><b>{item.hours_delta?`+${formatNumber(item.hours_delta,1)} h`:`${formatNumber(item.meter_hours,1)} h`}</b><small>{data.machineAssets.find(asset=>asset.id===item.machine_id)?.display_name??'Activo histórico'} · {eventDate(item.occurred_at)}</small><strong>{item.notes||'Sin observaciones'}</strong></div>)}</article>}
  </section>;
}

export function EconomyPanel({data}:{data:Workspace}){
  const recordEntry=useRecordFinancialEntry();
  const reverseEntry=useReverseFinancialEntry();
  const canWrite=['owner','admin'].includes(data.organization!.role);
  const [creating,setCreating]=useState(data.financialEntries.length===0&&canWrite);
  const [reverseTarget,setReverseTarget]=useState<string|null>(null);
  const currency=data.establishment!.base_currency||'ARS';
  const [form,setForm]=useState({direction:'expense',date:todayForInput(),category:'Insumos',amount:'',description:'',reference:'',parcelId:'',machineId:''});
  const [reversalReason,setReversalReason]=useState('');
  const reversedIds=useMemo(()=>new Set(data.financialEntries.map(entry=>entry.reversal_of).filter(Boolean)),[data.financialEntries]);
  const summary=data.operationalSummary;
  const income=Number(summary?.month_income??0),expense=Number(summary?.month_expense??0);

  function submit(event:FormEvent){event.preventDefault();recordEntry.mutate({establishmentId:data.establishment!.id,parcelId:form.parcelId||null,machineId:form.machineId||null,direction:form.direction as FinancialEntry['direction'],date:form.date,category:form.category,amount:Number(form.amount),currency,description:form.description,reference:form.reference},{onSuccess:()=>{setCreating(false);setForm({...form,amount:'',description:'',reference:''})}})}
  function submitReversal(event:FormEvent){event.preventDefault();if(!reverseTarget)return;reverseEntry.mutate({entryId:reverseTarget,reason:reversalReason},{onSuccess:()=>{setReverseTarget(null);setReversalReason('')}})}

  return <section className="operationsModule"><ModuleHeader eyebrow="LIBRO OPERATIVO" title="Economía" description={`Ingresos y egresos inmutables en ${currency}; una corrección crea su contrapartida trazable.`} action={()=>canWrite&&setCreating(value=>!value)} actionLabel={canWrite?(creating?'Cerrar carga':'Nuevo movimiento'):'Solo lectura'}/>
    <div className="operationsKpis"><article><small>INGRESOS DEL MES</small><strong>{formatMoney(income,currency)}</strong><span>Movimientos contabilizados</span></article><article><small>EGRESOS DEL MES</small><strong>{formatMoney(expense,currency)}</strong><span>Movimientos contabilizados</span></article><article className={income-expense<0?'warningKpi':''}><small>FLUJO NETO DEL MES</small><strong>{formatMoney(income-expense,currency)}</strong><span>Ingresos menos egresos; no equivale a resultado contable</span></article></div>
    {creating&&<form className="operationForm" onSubmit={submit}><div className="formTitle"><CircleDollarSign/><div><h3>Nuevo movimiento</h3><p>Solo propietarios y administradores pueden escribir el libro.</p></div></div><div className="operationGrid"><label>Tipo<select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="expense">Egreso</option><option value="income">Ingreso</option></select></label><label>Fecha<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Categoría<input required minLength={2} maxLength={80} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Importe ({currency})<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Lote<select value={form.parcelId} onChange={e=>setForm({...form,parcelId:e.target.value})}><option value="">General</option>{data.parcels.map(parcel=><option key={parcel.id} value={parcel.id}>{parcel.name}</option>)}</select></label><label>Maquinaria<select value={form.machineId} onChange={e=>setForm({...form,machineId:e.target.value})}><option value="">Sin asociar</option>{data.machineAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.display_name}</option>)}</select></label><label className="wideField">Descripción<textarea required minLength={2} maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Comprobante / referencia<input maxLength={120} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label></div><MutationError error={recordEntry.error}/><SubmitButton pending={recordEntry.isPending} label="Contabilizar movimiento"/></form>}
    {reverseTarget&&<form className="reversalForm" onSubmit={submitReversal}><RotateCcw/><div><h3>Crear contrapartida</h3><p>El asiento original no se elimina. Indicá el motivo de la corrección.</p><input required minLength={2} maxLength={300} value={reversalReason} onChange={e=>setReversalReason(e.target.value)} placeholder="Motivo de la reversión"/><MutationError error={reverseEntry.error}/></div><button disabled={reverseEntry.isPending}>{reverseEntry.isPending?'Procesando…':'Confirmar reversión'}</button></form>}
    <article className="ledgerPanel"><div className="ledgerHeader"><div><History/><span><b>Libro de movimientos</b><small>{data.financialEntries.length} asientos visibles</small></span></div><small>BASE {currency}</small></div>{data.financialEntries.length?data.financialEntries.map(entry=>{const reversed=reversedIds.has(entry.id);return <div className={`ledgerRow ${entry.reversal_of?'isReversal':''}`} key={entry.id}><span className={`ledgerDirection ${entry.direction}`}>{entry.direction==='income'?<ArrowUpRight/>:<ArrowDownRight/>}</span><div><b>{entry.description}</b><small>{entry.category} · {new Date(`${entry.occurred_on}T12:00:00`).toLocaleDateString('es-AR')}{entry.reference?` · ${entry.reference}`:''}</small></div><strong>{entry.direction==='income'?'+':'−'} {formatMoney(entry.amount,entry.currency)}</strong><span className="ledgerState">{entry.reversal_of?'Contrapartida':reversed?'Revertido':'Contabilizado'}</span>{canWrite&&!entry.reversal_of&&!reversed&&<button aria-label="Revertir movimiento" onClick={()=>setReverseTarget(entry.id)}><RotateCcw/></button>}</div>}):<div className="operationEmpty"><CircleDollarSign/><h3>El libro está vacío</h3><p>Registrá el primer movimiento real; no se generan valores simulados.</p></div>}</article>
  </section>;
}
