import { type FormEvent, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, CalendarDays, Check, ClipboardCheck, Clock3, Database, FileCheck2, Flag, LoaderCircle, RefreshCw, Rocket, ShieldCheck, Target, TrendingUp } from 'lucide-react';
import { useCapturePilotSnapshot, useLaunchPilot, usePilotControl, useRecordPilotValue, useReviewPilotValue, useTransitionPilot, type PilotMetric, type PilotProgram, type PilotSnapshot, type PilotValueCategory, type PilotValueClaim } from './lib/pilot';
import type { Workspace } from './lib/workspace';
import './pilot.css';

const metricLabels:Record<string,string>={monitored_hectares:'Superficie monitoreada',parcels_count:'Lotes conectados',reporting_devices:'Dispositivos con señal',sensor_readings:'Lecturas IoT',scouting_visits_created:'Recorridas creadas',scouting_visits_completed:'Recorridas completadas',scouting_cycle_hours:'Ciclo de recorrida',field_findings:'Hallazgos de campo',evidence_photos:'Evidencias fotográficas',work_orders_opened:'Órdenes abiertas',work_orders_completed:'Órdenes completadas',preventive_orders_completed:'Preventivos completados',maintenance_cost:'Costo de mantenimiento',operating_expense:'Egresos operativos',operating_income:'Ingresos operativos'};
const sumMetrics=new Set(['sensor_readings','scouting_visits_created','scouting_visits_completed','field_findings','evidence_photos','work_orders_opened','work_orders_completed','preventive_orders_completed','maintenance_cost','operating_expense','operating_income']);
const categoryLabels:Record<PilotValueCategory,string>={avoided_downtime:'Parada evitada',maintenance_saving:'Ahorro de mantenimiento',input_saving:'Ahorro de insumos',yield_protection:'Valor productivo protegido',labor_saving:'Ahorro de trabajo',other:'Otro valor'};
const statusLabels:Record<PilotProgram['status'],string>={active:'Activo',completed:'Completado',cancelled:'Cancelado'};

function errorText(error:unknown){return error instanceof Error?error.message:'Error inesperado'}
function localDate(value:string){return new Intl.DateTimeFormat('es-AR',{dateStyle:'medium'}).format(new Date(`${value}T12:00:00`))}
function daysBetween(start:string,end:string){return Math.max(1,Math.round((Date.parse(`${end}T12:00:00`)-Date.parse(`${start}T12:00:00`))/86_400_000)+1)}
function formatMetric(key:string,metric:PilotMetric|undefined,snapshot:PilotSnapshot|undefined,currency:string){
  if(!metric||metric.value===null)return 'Sin datos';
  const divisor=snapshot&&sumMetrics.has(key)?daysBetween(snapshot.window_start_on,snapshot.window_end_on):1;
  const value=Number(metric.value)/divisor;
  if(metric.unit===currency||/^[A-Z]{3}$/.test(metric.unit))return `${new Intl.NumberFormat('es-AR',{style:'currency',currency:metric.unit,maximumFractionDigits:0}).format(value)}${divisor>1?' / día':''}`;
  const suffix:Record<string,string>={ha:' ha',hours:' h',count:'',percent:'%'};
  return `${new Intl.NumberFormat('es-AR',{maximumFractionDigits:2}).format(value)}${suffix[metric.unit]??` ${metric.unit}`}${divisor>1?' / día':''}`;
}
function addDays(days:number){const date=new Date();date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)}

export function PilotControl({data}:{data:Workspace}){
  const establishment=data.establishment!;
  const manager=data.organization!.role==='owner'||data.organization!.role==='admin';
  const pilot=usePilotControl(establishment.id);
  const launch=useLaunchPilot(establishment.id);
  const capture=useCapturePilotSnapshot(establishment.id);
  const transition=useTransitionPilot(establishment.id);
  const recordValue=useRecordPilotValue(establishment.id);
  const reviewValue=useReviewPilotValue(establishment.id);
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [notice,setNotice]=useState<{tone:'ok'|'error';text:string}|null>(null);

  const program=useMemo(()=>pilot.data?.programs.find(item=>item.id===selectedId)??pilot.data?.programs[0]??null,[pilot.data,selectedId]);
  const snapshots=useMemo(()=>pilot.data?.snapshots.filter(item=>item.program_id===program?.id)??[],[pilot.data,program]);
  const claims=useMemo(()=>pilot.data?.claims.filter(item=>item.program_id===program?.id)??[],[pilot.data,program]);
  const baseline=snapshots.find(item=>item.snapshot_type==='baseline');
  const comparison=snapshots.find(item=>item.snapshot_type==='final')??snapshots.find(item=>item.snapshot_type==='current');

  async function action(run:()=>Promise<unknown>,success:string){setNotice(null);try{await run();setNotice({tone:'ok',text:success})}catch(error){setNotice({tone:'error',text:errorText(error)})}}
  if(pilot.isLoading)return <div className="mapLoading"><LoaderCircle className="spin"/>Cargando evidencia del piloto…</div>;
  if(pilot.error)return <section className="pilotError"><AlertTriangle/><h2>No pudimos cargar Pilot Control</h2><p>{errorText(pilot.error)}</p><button onClick={()=>pilot.refetch()}>Reintentar</button></section>;

  return <div className="pilotModule">
    <section className="pilotHero"><div><small>VALIDACIÓN DE MERCADO · EVIDENCIA OPERATIVA</small><h2>NODO Pilot Control</h2><p>Convierte adopción, operación y valor económico en evidencia trazable. Una medición no implica causalidad ni reemplaza validación contable o externa.</p></div><span><ShieldCheck/> Claims bajo control</span></section>
    {notice&&<div className={`pilotNotice ${notice.tone}`}>{notice.tone==='ok'?<Check/>:<AlertTriangle/>}{notice.text}</div>}
    {!program?<LaunchPilot manager={manager} busy={launch.isPending} onLaunch={input=>action(()=>launch.mutateAsync(input),'Piloto iniciado con línea base inmutable.')}/>:<>
      <section className="pilotToolbar"><div><span className={`pilotStatus ${program.status}`}>{statusLabels[program.status]}</span><h3>{program.name}</h3><p>{establishment.name} · {localDate(program.started_on)} → {localDate(program.target_end_on)}</p></div>{pilot.data!.programs.length>1&&<label>Programa<select value={program.id} onChange={event=>setSelectedId(event.target.value)}>{pilot.data!.programs.map(item=><option value={item.id} key={item.id}>{item.name} · {statusLabels[item.status]}</option>)}</select></label>}<div className="pilotToolbarActions">{program.status==='active'&&<button disabled={capture.isPending} onClick={()=>void action(()=>capture.mutateAsync(program.id),'Evidencia operativa actualizada.')}>{capture.isPending?<LoaderCircle className="spin"/>:<RefreshCw/>} Actualizar evidencia</button>}</div></section>
      <section className="pilotIntent"><article><Target/><div><small>HIPÓTESIS</small><p>{program.hypothesis}</p></div></article><article><Flag/><div><small>CRITERIO DE ÉXITO</small><p>{program.success_definition}</p></div></article></section>
      <PilotMetrics baseline={baseline} comparison={comparison} currency={establishment.base_currency}/>
      <section className="pilotGrid"><ValueLedger program={program} claims={claims} actorUserId={data.organization!.userId} manager={manager} currency={establishment.base_currency} busy={recordValue.isPending||reviewValue.isPending} onRecord={input=>action(()=>recordValue.mutateAsync(input),'Valor declarado; requiere revisión independiente.')} onReview={(input,accepted)=>action(()=>reviewValue.mutateAsync({...input,accepted}),accepted?'Claim validado internamente.':'Claim rechazado con trazabilidad.')}/><PilotGovernance program={program} snapshots={snapshots} manager={manager} busy={transition.isPending} onTransition={input=>action(()=>transition.mutateAsync(input),input.status==='completed'?'Piloto completado con captura final.':'Piloto cancelado con motivo auditado.')}/></section>
    </>}
  </div>;
}

function LaunchPilot({manager,busy,onLaunch}:{manager:boolean;busy:boolean;onLaunch:(input:{name:string;hypothesis:string;successDefinition:string;targetEnd:string;baselineDays:number})=>void}){
  const [name,setName]=useState('');const [hypothesis,setHypothesis]=useState('');const [success,setSuccess]=useState('');const [targetEnd,setTargetEnd]=useState(addDays(90));const [baselineDays,setBaselineDays]=useState(30);
  function submit(event:FormEvent){event.preventDefault();onLaunch({name,hypothesis,successDefinition:success,targetEnd,baselineDays})}
  if(!manager)return <section className="pilotEmpty"><Rocket/><h3>Aún no existe un piloto activo</h3><p>Un propietario o administrador debe definir hipótesis, ventana y criterio de éxito antes de medir.</p></section>;
  return <section className="launchPilot"><div className="launchStory"><Rocket/><small>PRIMERA PRUEBA COMERCIAL</small><h3>Iniciá un piloto medible</h3><p>NODO congelará automáticamente los {baselineDays} días previos como línea base. Los ceros se conservarán: pueden indicar ausencia real o falta de instrumentación.</p><ul><li>Una hipótesis concreta.</li><li>Un criterio observable.</li><li>Datos operativos y económicos separados de los claims.</li></ul></div><form onSubmit={submit}><label>Nombre del piloto<input required minLength={3} maxLength={120} value={name} onChange={event=>setName(event.target.value)} placeholder="Ej.: Reducir paradas de maquinaria"/></label><label>Hipótesis<textarea required minLength={20} maxLength={1000} value={hypothesis} onChange={event=>setHypothesis(event.target.value)} placeholder="Si digitalizamos mantenimiento y recorridas, entonces…"/></label><label>Criterio de éxito<textarea required minLength={20} maxLength={1000} value={success} onChange={event=>setSuccess(event.target.value)} placeholder="Consideraremos exitoso el piloto cuando…"/></label><div className="pilotFormRow"><label>Final objetivo<input type="date" required min={addDays(7)} max={addDays(365)} value={targetEnd} onChange={event=>setTargetEnd(event.target.value)}/></label><label>Línea base<select value={baselineDays} onChange={event=>setBaselineDays(Number(event.target.value))}><option value={14}>14 días</option><option value={30}>30 días</option><option value={60}>60 días</option><option value={90}>90 días</option></select></label></div><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Rocket/>} Iniciar y congelar línea base</button></form></section>;
}

function PilotMetrics({baseline,comparison,currency}:{baseline:PilotSnapshot|undefined;comparison:PilotSnapshot|undefined;currency:string}){
  const keys=['monitored_hectares','reporting_devices','scouting_visits_completed','scouting_cycle_hours','work_orders_completed','maintenance_cost','field_findings','evidence_photos'];
  return <section className="pilotEvidence"><div className="pilotSectionTitle"><div><small>MEDICIÓN SERVER-OWNED</small><h3>Línea base vs. operación</h3><p>{baseline?`Base ${localDate(baseline.window_start_on)}–${localDate(baseline.window_end_on)}`:'Sin línea base'} · {comparison?`${comparison.snapshot_type==='final'?'Final':'Actual'} ${localDate(comparison.window_start_on)}–${localDate(comparison.window_end_on)}`:'Actualizá evidencia para abrir la comparación'}</p></div><Database/></div><div className="pilotMetricGrid">{keys.map(key=><article key={key}><small>{metricLabels[key]}</small><div><span>BASE<b>{formatMetric(key,baseline?.metrics[key],baseline,currency)}</b></span><TrendingUp/><span>ACTUAL<b>{comparison?formatMetric(key,comparison.metrics[key],comparison,currency):'Pendiente'}</b></span></div><em>{baseline?.metrics[key]?.source??'Fuente no disponible'}</em></article>)}</div><p className="metricBoundary"><AlertTriangle/> Los acumulados se muestran por día para comparar ventanas distintas. La superficie y los dispositivos son estados de cobertura; el ciclo es un promedio.</p></section>;
}

function ValueLedger({program,claims,actorUserId,manager,currency,busy,onRecord,onReview}:{program:PilotProgram;claims:PilotValueClaim[];actorUserId:string;manager:boolean;currency:string;busy:boolean;onRecord:(input:{programId:string;category:PilotValueCategory;amount:number;calculationMethod:string;evidenceReference:string})=>void;onReview:(input:{claimId:string;note:string},accepted:boolean)=>void}){
  const [open,setOpen]=useState(false);const [category,setCategory]=useState<PilotValueCategory>('avoided_downtime');const [amount,setAmount]=useState('');const [method,setMethod]=useState('');const [evidence,setEvidence]=useState('');const [review,setReview]=useState<{id:string;note:string}|null>(null);
  function submit(event:FormEvent){event.preventDefault();onRecord({programId:program.id,category,amount:Number(amount),calculationMethod:method,evidenceReference:evidence});setOpen(false)}
  const verified=claims.filter(item=>item.status==='internally_verified').reduce((sum,item)=>sum+Number(item.amount),0);
  return <article className="valueLedger"><div className="pilotSectionTitle"><div><small>VALOR ECONÓMICO</small><h3>Claims de impacto</h3><p>{new Intl.NumberFormat('es-AR',{style:'currency',currency,maximumFractionDigits:0}).format(verified)} con verificación interna de dos personas.</p></div>{manager&&<button onClick={()=>setOpen(value=>!value)}>{open?'Cerrar':'Declarar valor'}</button>}</div>{open&&<form className="valueForm" onSubmit={submit}><div className="pilotFormRow"><label>Categoría<select value={category} onChange={event=>setCategory(event.target.value as PilotValueCategory)}>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Monto {currency}<input type="number" min="0.01" step="0.01" required value={amount} onChange={event=>setAmount(event.target.value)}/></label></div><label>Método de cálculo<textarea required minLength={20} maxLength={1500} value={method} onChange={event=>setMethod(event.target.value)} placeholder="Fórmula, supuestos y período comparado"/></label><label>Referencia de evidencia<input required minLength={5} maxLength={500} value={evidence} onChange={event=>setEvidence(event.target.value)} placeholder="Factura, orden, informe o ubicación documental"/></label><button disabled={busy}><FileCheck2/> Guardar como declarado</button></form>}{claims.length?<div className="claimList">{claims.map(claim=><div className="claimRow" key={claim.id}><div><small>{categoryLabels[claim.category]}</small><b>{new Intl.NumberFormat('es-AR',{style:'currency',currency:claim.currency}).format(Number(claim.amount))}</b><p>{claim.calculation_method}</p><em>Evidencia: {claim.evidence_reference}</em></div><span className={claim.status}>{claim.status==='declared'?'Declarado':claim.status==='internally_verified'?'Verificado internamente':'Rechazado'}</span>{claim.status==='declared'&&manager&&claim.claimed_by!==actorUserId&&(review?.id===claim.id?<div className="claimReview"><textarea minLength={10} placeholder="Conclusión de la revisión" value={review.note} onChange={event=>setReview({id:claim.id,note:event.target.value})}/><button disabled={busy||review.note.trim().length<10} onClick={()=>onReview({claimId:claim.id,note:review.note},true)}>Validar</button><button disabled={busy||review.note.trim().length<10} onClick={()=>onReview({claimId:claim.id,note:review.note},false)}>Rechazar</button></div>:<button onClick={()=>setReview({id:claim.id,note:''})}><ClipboardCheck/> Revisar</button>)}</div>)}</div>:<div className="pilotNoData"><BarChart3/><p>No hay valor declarado. Eso es más confiable que un ROI inventado.</p></div>}</article>;
}

function PilotGovernance({program,snapshots,manager,busy,onTransition}:{program:PilotProgram;snapshots:PilotSnapshot[];manager:boolean;busy:boolean;onTransition:(input:{programId:string;status:'completed'|'cancelled';note:string})=>void}){
  const [closing,setClosing]=useState<'completed'|'cancelled'|null>(null);const [note,setNote]=useState('');const latest=snapshots[0];const remaining=Math.ceil((Date.parse(`${program.target_end_on}T12:00:00`)-Date.now())/86_400_000);
  return <article className="pilotGovernance"><div className="pilotSectionTitle"><div><small>GOBIERNO DEL PILOTO</small><h3>Calidad y cierre</h3><p>Sin sobreafirmaciones, con snapshot final inmutable.</p></div><ShieldCheck/></div><dl><dt><CalendarDays/> Días hasta objetivo</dt><dd>{program.status==='active'?Math.max(0,remaining):'—'}</dd><dt><Clock3/> Última captura</dt><dd>{latest?new Date(latest.captured_at).toLocaleString('es-AR'):'—'}</dd><dt><Database/> Versión de fuente</dt><dd>{latest?.source_version??'—'}</dd><dt><FileCheck2/> Capturas</dt><dd>{snapshots.length}</dd></dl><div className="limitationList">{(latest?.limitations??[]).map(item=><p key={item}><AlertTriangle/>{item}</p>)}</div>{program.status==='active'&&manager&&(closing?<div className="closePilot"><textarea minLength={10} maxLength={1000} value={note} onChange={event=>setNote(event.target.value)} placeholder="Motivo y conclusión del cierre"/><button disabled={busy||note.trim().length<10} onClick={()=>onTransition({programId:program.id,status:closing,note})}>{closing==='completed'?'Confirmar cierre':'Confirmar cancelación'}</button><button onClick={()=>setClosing(null)}>Volver</button></div>:<div className="pilotCloseActions"><button onClick={()=>setClosing('completed')}><Check/> Completar piloto</button><button className="secondary" onClick={()=>setClosing('cancelled')}>Cancelar piloto</button></div>)}</article>;
}
