import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Check, Clipboard, CloudSun, Cpu, Droplets, Gauge, LoaderCircle, Radio, Satellite, Sprout, Thermometer, Wifi, WifiOff } from 'lucide-react';
import { deviceConnectionState, useProvisionDevice, type Device, type SensorReading, type Workspace } from './lib/workspace';

const KIND_LABELS:Record<string,string>={gateway:'Gateway NODO',weather:'Estación meteorológica',soil:'Sonda de suelo',rfid:'Lector RFID',camera:'Cámara',machine:'Telemetría de máquina',water:'Sensor de agua'};
const METRIC_LABELS:Record<string,string>={'soil.moisture':'Humedad de suelo','soil.temperature':'Temperatura de suelo','air.temperature':'Temperatura ambiente','air.humidity':'Humedad ambiente','rain.total':'Lluvia acumulada','water.level':'Nivel de agua','battery.voltage':'Batería','machine.hours':'Horas de máquina'};

function kindIcon(kind:string){if(kind==='soil')return Sprout;if(kind==='weather')return CloudSun;if(kind==='water')return Droplets;if(kind==='gateway')return Satellite;if(kind==='machine')return Gauge;return Cpu}
function metricIcon(metric:string){if(metric.includes('temperature'))return Thermometer;if(metric.includes('moisture')||metric.includes('humidity')||metric.includes('rain')||metric.includes('water'))return Droplets;return Gauge}
function formatUnit(unit:string){return unit==='pct'?'%':unit==='celsius'||unit==='degC'?'°C':unit}
function relativeTime(value:string|null){if(!value)return'Nunca reportó';const timestamp=Date.parse(value);if(!Number.isFinite(timestamp))return'Fecha inválida';const elapsed=Math.max(0,Date.now()-timestamp);const minutes=Math.floor(elapsed/60_000);if(minutes<1)return'Hace menos de 1 min';if(minutes<60)return`Hace ${minutes} min`;const hours=Math.floor(minutes/60);if(hours<48)return`Hace ${hours} h`;return`Hace ${Math.floor(hours/24)} d`}

function DeviceReading({reading}:{reading:SensorReading}){const Icon=metricIcon(reading.metric);return <div className="sensorReading"><span><Icon/></span><div><small>{METRIC_LABELS[reading.metric]??reading.metric}</small><strong>{reading.value.toLocaleString('es-AR',{maximumFractionDigits:2})} {formatUnit(reading.unit)}</strong><p>{relativeTime(reading.observed_at)} · calidad {reading.quality}%</p></div></div>}

function DeviceCard({device,readings,parcelName}:{device:Device;readings:SensorReading[];parcelName:string}){const Icon=kindIcon(device.kind);const state=deviceConnectionState(device);return <article className="deviceCard"><div className="deviceHeader"><span><Icon/></span><div><small>{KIND_LABELS[device.kind]??device.kind}</small><h3>{device.display_name}</h3><p>{parcelName} · {device.external_id}</p></div><em className={`deviceState ${state}`}>{state==='online'?<Wifi/>:<WifiOff/>}{state==='online'?'En línea':state==='offline'?'Sin señal':state==='retired'?'Retirado':'Esperando datos'}</em></div><div className="deviceReadings">{readings.length?readings.slice(0,4).map(reading=><DeviceReading key={`${reading.device_id}-${reading.metric}`} reading={reading}/>):<div className="noReadings"><Radio/><span>Aún no recibió telemetría</span><small>Intervalo esperado: {device.expected_interval_minutes} min</small></div>}</div><footer><span>Último enlace: {relativeTime(device.last_seen_at)}</span><span>Instalado {new Date(device.installed_at).toLocaleDateString('es-AR')}</span></footer></article>}

function createExternalId(kind:string){return `nodo-${kind}-${crypto.randomUUID().slice(0,8)}`}

function ProvisionDevice({data,onClose}:{data:Workspace;onClose:()=>void}){
  const provision=useProvisionDevice();
  const [copied,setCopied]=useState(false);
  const [copyError,setCopyError]=useState('');
  const [form,setForm]=useState(()=>({displayName:'',kind:'soil',externalId:createExternalId('soil'),parcelId:'',intervalMinutes:'60'}));
  const endpoint=`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ingest-telemetry`;
  useEffect(()=>()=>provision.reset(),[provision.reset]);
  function submit(event:FormEvent){event.preventDefault();provision.mutate({establishmentId:data.establishment!.id,displayName:form.displayName,kind:form.kind,externalId:form.externalId,parcelId:form.parcelId||null,intervalMinutes:Number(form.intervalMinutes)})}
  async function copyConfiguration(){if(!provision.data)return;try{await navigator.clipboard.writeText(JSON.stringify({endpoint,headers:{'x-device-token':provision.data.token},example:{readings:[{observed_at:new Date().toISOString(),metric:'soil.moisture',value:31.2,unit:'pct',quality:98}]}},null,2));setCopied(true);setCopyError('')}catch(error){setCopyError(error instanceof Error?error.message:'No se pudo copiar la configuración')}}
  if(provision.data)return <section className="provisionSuccess"><span><Check/></span><small>DISPOSITIVO CREADO</small><h2>Guardá la credencial en el gateway</h2><p>Este token se muestra una sola vez. NODO guarda únicamente su huella criptográfica y no puede recuperarlo después.</p><code>{provision.data.token}</code><button className="copyConfig" onClick={()=>void copyConfiguration()}><Clipboard/>{copied?'Configuración copiada':'Copiar configuración de ingesta'}</button>{copyError&&<p className="formError">{copyError}</p>}<div className="endpointPreview"><small>ENDPOINT</small><span>{endpoint}</span></div><button className="finishProvision" onClick={()=>{provision.reset();onClose()}}>Listo, ya guardé la credencial</button></section>;
  return <section className="provisionDevice"><div className="provisionIntro"><small>ALTA SEGURA</small><h2>Conectar un dispositivo</h2><p>Crearemos una identidad independiente para el hardware. El sensor no utiliza tu sesión ni la clave pública del navegador.</p><div><Radio/><span>Token SHA-256 · aislado por organización · revocable</span></div></div><form onSubmit={submit}><label>Nombre visible<input required minLength={2} maxLength={100} value={form.displayName} onChange={event=>setForm({...form,displayName:event.target.value})} placeholder="Ej. Sonda humedad Lote Bajo"/></label><div className="sensorFormGrid"><label>Tipo<select value={form.kind} onChange={event=>setForm({...form,kind:event.target.value})}><option value="soil">Sonda de suelo</option><option value="weather">Estación meteorológica</option><option value="gateway">Gateway NODO</option><option value="water">Sensor de agua</option><option value="rfid">Lector RFID</option><option value="machine">Telemetría de máquina</option><option value="camera">Cámara</option></select></label><label>Lote<select value={form.parcelId} onChange={event=>setForm({...form,parcelId:event.target.value})}><option value="">Todo el establecimiento</option>{data.parcels.map(parcel=><option key={parcel.id} value={parcel.id}>{parcel.name}</option>)}</select></label></div><div className="sensorFormGrid"><label>Intervalo esperado<select value={form.intervalMinutes} onChange={event=>setForm({...form,intervalMinutes:event.target.value})}><option value="15">Cada 15 minutos</option><option value="30">Cada 30 minutos</option><option value="60">Cada hora</option><option value="180">Cada 3 horas</option><option value="1440">Una vez al día</option></select></label><label>Identificador técnico<input required minLength={2} maxLength={100} value={form.externalId} onChange={event=>setForm({...form,externalId:event.target.value})}/></label></div>{provision.error&&<p className="formError">{provision.error instanceof Error?provision.error.message:'No se pudo provisionar el dispositivo'}</p>}<div className="provisionActions"><button type="button" onClick={onClose}>Cancelar</button><button className="primaryButton" disabled={provision.isPending||form.displayName.trim().length<2}>{provision.isPending?<LoaderCircle className="spin"/>:<><Radio/> Crear identidad del sensor</>}</button></div></form></section>
}

export function SensorsPanel({data}:{data:Workspace}){
  const [provisioning,setProvisioning]=useState(false);
  const readingsByDevice=useMemo(()=>new Map(data.devices.map(device=>[device.id,data.sensorReadings.filter(reading=>reading.device_id===device.id)])),[data.devices,data.sensorReadings]);
  const online=data.devices.filter(device=>deviceConnectionState(device)==='online').length;
  const canProvision=['owner','admin'].includes(data.organization!.role);
  if(provisioning)return <ProvisionDevice data={data} onClose={()=>setProvisioning(false)}/>;
  return <section className="sensorsModule"><div className="moduleToolbar"><div><small>RED NODO</small><h2>Sensores y telemetría</h2><p>Lecturas persistidas desde hardware autenticado; actualización automática cada minuto.</p></div>{canProvision&&<button onClick={()=>setProvisioning(true)}>Conectar sensor</button>}</div><div className="sensorStats"><article><Radio/><div><small>DISPOSITIVOS</small><b>{data.devices.length}</b><span>identidades registradas</span></div></article><article><Wifi/><div><small>EN LÍNEA</small><b>{online}</b><span>según intervalo esperado</span></div></article><article><Gauge/><div><small>SEÑALES</small><b>{data.sensorReadings.length}</b><span>últimas métricas distintas</span></div></article></div>{data.devices.length?<div className="deviceGrid">{data.devices.map(device=><DeviceCard key={device.id} device={device} readings={readingsByDevice.get(device.id)??[]} parcelName={data.parcels.find(parcel=>parcel.id===device.parcel_id)?.name??'Establecimiento'}/>)}</div>:<article className="sensorsEmpty"><span><Radio/></span><small>INFRAESTRUCTURA LISTA</small><h2>Conectá la primera señal del campo</h2><p>Una estación, sonda, gateway, lector RFID o máquina puede enviar lecturas con su propia credencial. No mostramos datos simulados.</p>{canProvision?<button onClick={()=>setProvisioning(true)}>Provisionar primer dispositivo</button>:<em>Un owner o administrador debe provisionar el hardware.</em>}</article>}</section>
}
